version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  
  disable:
    - errcheck

formatters:
  enable:
    - gofmt
    - goimports
    - golines