// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

// AppError Represents an application error with standardized fields for consistent error handling and user communication
type AppError struct {
	// Code A unique identifier for the error type, useful for programmatic error handling and internationalization
	Code string `json:"code"`

	// Message A detailed explanation of what went wrong, suitable for display to users
	Message string `json:"message"`

	// Title A brief, human-readable summary of the error
	Title string `json:"title"`
}

// RefreshTokenRequest Request payload for refreshing an expired access token
type RefreshTokenRequest struct {
	// RefreshToken Valid JWT refresh token obtained from `/authorize` or previous refresh
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenResponse Response containing new authentication tokens after successful token refresh
type RefreshTokenResponse struct {
	// AccessToken New JWT access token
	AccessToken string `json:"access_token"`

	// RefreshToken New JWT refresh token
	RefreshToken string `json:"refresh_token"`
}

// DefaultServer Represents an application error with standardized fields for consistent error handling and user communication
type DefaultServer = AppError

// PostRefreshTokenJSONRequestBody defines body for PostRefreshToken for application/json ContentType.
type PostRefreshTokenJSONRequestBody = RefreshTokenRequest
