name: CI

run-name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      
      - name: Test
        run: go test -v -race ./...
  
  result:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: echo "Done!"
